{% set name = "linkedin-scraper" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/joeyism/linkedin_scraper/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b733cff3b7b3c6970e389d8c3fde4ab0d63afc9172ab5d60814d04ba74323290

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - lxml
    - python >={{ python_min }}
    - requests
    - selenium
    - playwright-python
    - python-dotenv

test:
  imports:
    - linkedin_scraper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joeyism/linkedin_scraper
  summary: Scrapes user data from Linkedin
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
