{% set name = "linkedin-scraper" %}
{% set version = "2.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linkedin_scraper-{{ version }}.tar.gz
  sha256: 3d2baea650e3edd46f85145f142480b08efc7c8c8111ac770c6df3254f205ef3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - python >=3.6
    - requests
    - selenium

test:
  imports:
    - linkedin_scraper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joeyism/linkedin_scraper
  summary: Scrapes user data from Linkedin
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
