{% set name = "linkedin-scraper" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/joeyism/linkedin_scraper/archive/refs/tags/{{ version }}.tar.gz
  sha256: 84dfccb112e8aef1b6e195f57f71799b778670133ecfe68cb3f4504c47744925

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - lxml
    - python >={{ python_min }}
    - requests
    - selenium
    - playwright-python
    - python-dotenv
    - pydantic
    - aiofiles

test:
  imports:
    - linkedin_scraper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joeyism/linkedin_scraper
  summary: Scrapes user data from Linkedin
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
