{% set name = "linkedin-scraper" %}
{% set version = "2.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/joeyism/linkedin_scraper/archive/refs/tags/{{ version }}.tar.gz
  sha256: eacedd19b62cb7c2df12ae43919cbba49a6f855305a9978ad69cd79ebdd9a794

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - python >=3.6
    - requests
    - selenium

test:
  imports:
    - linkedin_scraper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joeyism/linkedin_scraper
  summary: Scrapes user data from Linkedin
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
